import {
  FilterType,
  HeaterType,
  PoolShape,
  PumpSpeedType,
  SanitizerType,
} from "@/types/property";
import type { PropertyWithRelations } from "@/types/property";

export const MOCK_PROPERTIES: PropertyWithRelations[] = [
  {
    id: "prop-001",
    tenant_id: "tenant-showtime",
    ghl_contact_id: "ghl-cnt-rodriguez-001",
    customer_name: "Rodriguez",
    address_line1: "1234 Sunset Blvd",
    city: "Los Angeles",
    state: "CA",
    zip: "90028",
    gate_code: "2847",
    access_notes: "Gate is on the left side of the house. Small dog (Chihuahua) in the backyard — harmless but noisy. Park on the street.",
    service_notes: "Customer prefers service before 10am. Always check salt cell after service. Run pump on high speed for 30 min after chemical add.",
    pool_equipment: {
      pool_size_gallons: 28000,
      pool_shape: PoolShape.FREEFORM,
      pump: {
        make: "Pentair",
        model: "SuperFlo VS",
        serial_number: "PNT-SF-2841-A",
        install_date: "2022-03-15",
        type: PumpSpeedType.VARIABLE_SPEED,
        hp: 1.5,
      },
      filter: {
        make: "Pentair",
        model: "Clean & Clear Plus",
        serial_number: "PNT-CC-420-B",
        install_date: "2022-03-15",
        type: FilterType.CARTRIDGE,
        size_sq_ft: 420,
      },
      sanitizer: {
        make: "Hayward",
        model: "Aqua Rite Pro",
        serial_number: "HWD-AR-991-X",
        install_date: "2022-03-15",
        type: SanitizerType.SALTWATER,
      },
      automation: {
        make: "Pentair",
        model: "IntelliCenter",
        serial_number: "PNT-IC-3301-Z",
        install_date: "2022-03-15",
      },
      additional_notes: "Salt cell replaced Feb 2025. Target salt level 3200 ppm.",
      last_updated: "2026-04-27T09:15:00Z",
    },
    is_active: true,
    created_at: "2022-03-10T08:00:00Z",
    updated_at: "2026-04-27T09:15:00Z",
    active_work_order_count: 1,
    last_service_date: "2026-04-27",
    last_service_technician_name: "Carlos M.",
  },

  {
    id: "prop-002",
    tenant_id: "tenant-showtime",
    ghl_contact_id: "ghl-cnt-park-001",
    customer_name: "Park",
    address_line1: "887 Wilshire Dr",
    city: "Beverly Hills",
    state: "CA",
    zip: "90210",
    gate_code: "5519#",
    access_notes: "Electric gate — enter code then press #. Must close gate on exit. Security camera above the gate.",
    service_notes: "Owner is very particular about water clarity. Always test and record chemical levels before leaving. Text office if any equipment looks off.",
    pool_equipment: {
      pool_size_gallons: 22000,
      pool_shape: PoolShape.RECTANGLE,
      pump: {
        make: "Hayward",
        model: "Super Pump",
        serial_number: "HWD-SP-1104-C",
        install_date: "2018-06-20",
        type: PumpSpeedType.SINGLE_SPEED,
        hp: 1.5,
        notes: "Motor burned out — replacement scheduled (WO-0002). Do not run until replaced.",
      },
      filter: {
        make: "Hayward",
        model: "Pro-Grid",
        serial_number: "HWD-PG-60-D",
        install_date: "2018-06-20",
        type: FilterType.DE,
        size_sq_ft: 60,
      },
      heater: {
        make: "Raypak",
        model: "R-407A",
        serial_number: "RAY-407-2019-E",
        install_date: "2019-11-01",
        type: HeaterType.GAS,
        btu_output: 407000,
      },
      sanitizer: {
        type: SanitizerType.CHLORINE,
        notes: "Trichlor tabs in floating dispenser. Shock every other week.",
      },
      additional_notes: "Pool was resurfaced with Pebble Tec in 2020. Do not use abrasive brushes.",
      last_updated: "2026-05-05T11:00:00Z",
    },
    is_active: true,
    created_at: "2018-06-15T10:00:00Z",
    updated_at: "2026-05-05T11:00:00Z",
    active_work_order_count: 1,
    last_service_date: "2026-04-15",
    last_service_technician_name: "Sarah K.",
  },

  {
    id: "prop-003",
    tenant_id: "tenant-showtime",
    customer_name: "Mitchell",
    address_line1: "456 Pacific Ave",
    city: "Santa Monica",
    state: "CA",
    zip: "90401",
    access_notes: "Side gate is always unlocked. No dogs. Plenty of street parking on Pacific Ave.",
    service_notes: "New customer as of April 2026. Equipment survey completed during first visit. Heater installation scheduled.",
    pool_equipment: {
      pool_size_gallons: 35000,
      pool_shape: PoolShape.FREEFORM,
      pump: {
        make: "Jandy",
        model: "VS FloPro",
        serial_number: "JAN-VF-1882-G",
        install_date: "2021-08-10",
        type: PumpSpeedType.VARIABLE_SPEED,
        hp: 2.0,
      },
      filter: {
        make: "Jandy",
        model: "DEV Series",
        serial_number: "JAN-DEV-60-H",
        install_date: "2021-08-10",
        type: FilterType.CARTRIDGE,
        size_sq_ft: 320,
      },
      heater: {
        make: "Hayward",
        model: "HeatPro HP50HA1",
        serial_number: "TBD — awaiting delivery",
        type: HeaterType.ELECTRIC_HEAT_PUMP,
        btu_output: 50000,
        notes: "Unit delivered on-site. Installation scheduled for WO-0003.",
      },
      sanitizer: {
        make: "Hayward",
        model: "Aqua Rite",
        serial_number: "HWD-AR-2021-J",
        install_date: "2021-08-10",
        type: SanitizerType.SALTWATER,
      },
      automation: {
        make: "Jandy",
        model: "iAqualink 3.0",
        serial_number: "JAN-IAQ-3-2021-K",
        install_date: "2021-08-10",
      },
      last_updated: "2026-05-03T14:00:00Z",
    },
    is_active: true,
    created_at: "2026-04-01T09:00:00Z",
    updated_at: "2026-05-03T14:00:00Z",
    active_work_order_count: 1,
    last_service_technician_name: "Carlos M.",
  },

  {
    id: "prop-004",
    tenant_id: "tenant-showtime",
    customer_name: "Anderson",
    address_line1: "2200 Malibu Canyon Rd",
    city: "Malibu",
    state: "CA",
    zip: "90265",
    gate_code: "4821",
    access_notes: "Long private driveway — 0.3 miles from main road. Gate code 4821. Pool is behind the main house on the ocean-facing side. Watch for deer.",
    service_notes: "Vacation home — owner may not be present. Always photograph pool before and after service. Cell service is poor; call from the main road if needed.",
    pool_equipment: {
      pool_size_gallons: 18000,
      pool_shape: PoolShape.RECTANGLE,
      pump: {
        make: "Pentair",
        model: "WhisperFlo",
        serial_number: "PNT-WF-0842-L",
        install_date: "2020-05-15",
        type: PumpSpeedType.DUAL_SPEED,
        hp: 2.0,
      },
      filter: {
        make: "Pentair",
        model: "Triton II",
        serial_number: "PNT-T2-S140-M",
        install_date: "2020-05-15",
        type: FilterType.SAND,
        size_sq_ft: 3,
        notes: "Sand last replaced 2023. Next replacement due ~2027.",
      },
      sanitizer: {
        type: SanitizerType.CHLORINE,
        notes: "Liquid chlorine only — owner requested no tabs due to CYA buildup.",
      },
      additional_notes: "Pool turned green — algae bloom (WO-0004). Pump was running but filter appeared bypassed. Likely cause: backwash valve stuck in partially open position.",
      last_updated: "2026-05-04T07:15:00Z",
    },
    is_active: true,
    created_at: "2020-05-10T11:00:00Z",
    updated_at: "2026-05-04T07:15:00Z",
    active_work_order_count: 1,
  },

  {
    id: "prop-005",
    tenant_id: "tenant-showtime",
    ghl_contact_id: "ghl-cnt-thompson-001",
    customer_name: "Thompson",
    address_line1: "312 Ocean Front Walk",
    city: "Venice",
    state: "CA",
    zip: "90291",
    access_notes: "Beachfront property. Enter from the alley behind Ocean Front Walk. Gate code is the last 4 of the phone number on file. No parking in the alley — use the public lot on Windward Ave.",
    service_notes: "High-use pool — used daily. Check and adjust chemicals every visit even if scheduled for light maintenance. Owner prefers ozone system over heavy chemical use.",
    pool_equipment: {
      pool_size_gallons: 40000,
      pool_shape: PoolShape.LAP,
      pump: {
        make: "Pentair",
        model: "IntelliFlo3 VSF",
        serial_number: "PNT-IF3-4401-N",
        install_date: "2023-09-01",
        type: PumpSpeedType.VARIABLE_SPEED,
        hp: 3.0,
      },
      filter: {
        make: "Pentair",
        model: "Clean & Clear Plus",
        serial_number: "PNT-CC-520-P",
        install_date: "2023-09-01",
        type: FilterType.CARTRIDGE,
        size_sq_ft: 520,
        notes: "4 cartridges. One replaced under warranty May 2026 (WO-0005).",
      },
      heater: {
        make: "AquaCal",
        model: "TropiCal T135",
        serial_number: "AQC-T135-2023-Q",
        install_date: "2023-09-01",
        type: HeaterType.ELECTRIC_HEAT_PUMP,
        btu_output: 110000,
      },
      sanitizer: {
        make: "Del Ozone",
        model: "Eclipse 3",
        serial_number: "DEL-E3-2023-R",
        install_date: "2023-09-01",
        type: SanitizerType.OZONE,
        notes: "Supplemental liquid chlorine to maintain 1.0–2.0 ppm residual.",
      },
      automation: {
        make: "Pentair",
        model: "IntelliCenter G3",
        serial_number: "PNT-ICG3-2023-S",
        install_date: "2023-09-01",
      },
      additional_notes: "Premium setup — full Pentair ecosystem. All controllable via IntelliCenter app. Owner monitors remotely.",
      last_updated: "2026-05-03T15:05:00Z",
    },
    is_active: true,
    created_at: "2023-08-20T14:00:00Z",
    updated_at: "2026-05-03T15:05:00Z",
    active_work_order_count: 0,
    last_service_date: "2026-05-03",
    last_service_technician_name: "Sarah K.",
  },
];
