import {
  WorkOrderStatus,
  Priority,
  ServiceCategory,
  EstimateHandoffStatus,
} from "@/types/work-order";
import type { WorkOrderWithRelations } from "@/types/work-order";

export const MOCK_WORK_ORDERS: WorkOrderWithRelations[] = [
  {
    id: "wo-001",
    wo_number: "WO-0001",
    tenant_id: "tenant-showtime",
    property_id: "prop-001",
    title: "Weekly Pool Service",
    description: "Routine weekly maintenance — skim, brush, vacuum, check chemicals. Note: customer mentioned the water looked slightly cloudy last week.",
    status: WorkOrderStatus.IN_PROGRESS,
    priority: Priority.NORMAL,
    service_category: ServiceCategory.WEEKLY_POOL_MAINTENANCE,
    estimate_handoff_status: EstimateHandoffStatus.NOT_NEEDED,
    assigned_technician_id: "tech-001",
    scheduled_date: "2026-05-04",
    scheduled_time_start: "08:00",
    scheduled_time_end: "09:00",
    created_at: "2026-05-01T10:00:00Z",
    updated_at: "2026-05-04T08:30:00Z",
    property_address: "1234 Sunset Blvd, Los Angeles, CA 90028",
    property_customer_name: "Rodriguez",
    assigned_technician_name: "Carlos M.",
  },
  {
    id: "wo-002",
    wo_number: "WO-0002",
    tenant_id: "tenant-showtime",
    property_id: "prop-002",
    ghl_contact_id: "ghl-cnt-park-001",
    ghl_opportunity_id: "ghl-opp-park-pump-001",
    title: "Pool Pump Replacement",
    description: "Customer reported pump not turning on. Diagnosed on-site — motor burned out. Full replacement needed. Part # Hayward SP2607X10.",
    status: WorkOrderStatus.ESTIMATE_NEEDED,
    priority: Priority.HIGH,
    service_category: ServiceCategory.POOL_REPAIR,
    estimate_handoff_status: EstimateHandoffStatus.FLAGGED,
    assigned_technician_id: "tech-002",
    scheduled_date: "2026-05-05",
    scheduled_time_start: "10:00",
    scheduled_time_end: "11:30",
    created_at: "2026-05-02T09:00:00Z",
    updated_at: "2026-05-05T11:00:00Z",
    property_address: "887 Wilshire Dr, Beverly Hills, CA 90210",
    property_customer_name: "Park",
    assigned_technician_name: "Sarah K.",
  },
  {
    id: "wo-003",
    wo_number: "WO-0003",
    tenant_id: "tenant-showtime",
    property_id: "prop-003",
    title: "Heater Installation",
    description: "Install new Hayward heat pump HP50HA1. Equipment delivered on-site. Customer wants installation before weekend.",
    status: WorkOrderStatus.ASSIGNED,
    priority: Priority.NORMAL,
    service_category: ServiceCategory.EQUIPMENT_INSTALLATION,
    estimate_handoff_status: EstimateHandoffStatus.NOT_NEEDED,
    assigned_technician_id: "tech-001",
    scheduled_date: "2026-05-07",
    scheduled_time_start: "09:00",
    scheduled_time_end: "13:00",
    created_at: "2026-05-03T14:00:00Z",
    updated_at: "2026-05-03T14:00:00Z",
    property_address: "456 Pacific Ave, Santa Monica, CA 90401",
    property_customer_name: "Mitchell",
    assigned_technician_name: "Carlos M.",
  },
  {
    id: "wo-004",
    wo_number: "WO-0004",
    tenant_id: "tenant-showtime",
    property_id: "prop-004",
    title: "Emergency — Green Pool",
    description: "Pool turned green overnight. Possible algae bloom after pump failure. Customer requesting same-day service. Gate code: 4821.",
    status: WorkOrderStatus.NEW,
    priority: Priority.URGENT,
    service_category: ServiceCategory.EMERGENCY_SERVICE,
    estimate_handoff_status: EstimateHandoffStatus.NOT_NEEDED,
    scheduled_date: "2026-05-04",
    created_at: "2026-05-04T07:15:00Z",
    updated_at: "2026-05-04T07:15:00Z",
    property_address: "2200 Malibu Canyon Rd, Malibu, CA 90265",
    property_customer_name: "Anderson",
  },
  {
    id: "wo-005",
    wo_number: "WO-0005",
    tenant_id: "tenant-showtime",
    property_id: "prop-005",
    title: "Filter Deep Clean",
    description: "Annual cartridge filter cleaning and inspection. All 4 cartridges cleaned, one showing wear — replaced under warranty.",
    status: WorkOrderStatus.COMPLETED,
    priority: Priority.LOW,
    service_category: ServiceCategory.FILTER_CLEANING,
    estimate_handoff_status: EstimateHandoffStatus.NOT_NEEDED,
    assigned_technician_id: "tech-002",
    scheduled_date: "2026-05-03",
    scheduled_time_start: "14:00",
    scheduled_time_end: "15:00",
    completed_at: "2026-05-03T15:05:00Z",
    created_at: "2026-04-28T11:00:00Z",
    updated_at: "2026-05-03T15:05:00Z",
    property_address: "312 Ocean Front Walk, Venice, CA 90291",
    property_customer_name: "Thompson",
    assigned_technician_name: "Sarah K.",
  },
];
